import { MigrationData } from "../migration";

export default {
  name: "3",
  up: `
  create table if not exists Event_OnShot
  (
      id                         UInt128,
      onBattleStartId            UInt128,
      localtime                  DateTime64(3),
      dateTime                   DateTime64(3),
      shotId                     UInt32,
      shellTag                   String,
      shellName                  String,
      shellDamage                UInt16,
      shellPiercingPower         UInt16,
      shellCaliber               UInt16,
      shellSpeed                 UInt16,
      shellMaxDistance           UInt16,
      gunDispersion              Float32,
      battleDispersion           Float32,
      serverShotDispersion       Float32,
      clientShotDispersion       Float32,
      ballisticResultServer_r     Float32,
      ballisticResultServer_theta Float32,
      ballisticResultClient_r     Float32,
      ballisticResultClient_theta Float32,
      gravity                    Float32,
      serverAim                  UInt8,        -- Boolean type represented as UInt8
      autoAim                    UInt8,        -- Boolean type represented as UInt8
      ping                       Float32,
      fps                        UInt16,
      hitVehicleDescr            Nullable(UInt32),
      hitChassisDescr            Nullable(UInt32),
      hitTurretDescr             Nullable(UInt32),
      hitGunDescr                Nullable(UInt32),
      hitTurretYaw               Nullable(Float32),
      hitTurretPitch             Nullable(Float32),
      vehicleDescr               UInt32,
      chassisDescr               UInt32,
      turretDescr                UInt32,
      gunDescr                   UInt32,
      turretYaw                  Float32,
      turretPitch                Float32,
      shellDescr                 UInt32,
      hitSegment                 Nullable(String),
      vehicleSpeed               Float32,
      vehicleRotationSpeed       Float32,
      turretSpeed                Float32,
      gunPoint_x                 Float32,
      gunPoint_y                 Float32,
      gunPoint_z                 Float32,
      clientMarkerPoint_x        Float32,
      clientMarkerPoint_y        Float32,
      clientMarkerPoint_z        Float32,
      serverMarkerPoint_x        Float32,
      serverMarkerPoint_y        Float32,
      serverMarkerPoint_z        Float32,
      tracerStart_x              Float32,
      tracerStart_y              Float32,
      tracerStart_z              Float32,
      tracerEnd_x                Float32,
      tracerEnd_y                Float32,
      tracerEnd_z                Float32,
      tracerVel_x                Float32,
      tracerVel_y                Float32,
      tracerVel_z                Float32,
      hitReason                  Enum('tank' = 1, 'terrain' = 2, 'other' = 3, 'none' = 4),
      hitPoint_x                 Nullable(Float32) default NULL,
      hitPoint_y                 Nullable(Float32) default NULL,
      hitPoint_z                 Nullable(Float32) default NULL,
      \`results.order\`            Array(UInt32),
      \`results.tankTag\`          Array(String),
      \`results.shotDamage\`       Array(UInt16),
      \`results.fireDamage\`       Array(UInt16),
      \`results.shotHealth\`       Array(Nullable(UInt16)),
      \`results.fireHealth\`       Array(Nullable(UInt16)),
      \`results.ammoBayDestroyed\` Array(UInt8), -- Boolean type represented as UInt8
      \`results.flags\`            Array(UInt16),
      arenaTag                   String,
      playerName                 String,
      battleMode                 String,
      battleGameplay             String,
      serverName                 String,
      region                     String,
      gameVersion                String,
      team                       UInt8,
      tankTag                    String,
      tankType                   String,
      tankLevel                  UInt8,
      gunTag                     String,
      battleTime                 UInt32
  ) engine MergeTree() order by dateTime;
  `,
  down: `
    drop table if exists Event_OnShot;
  `
} as MigrationData